### ISSUE TITLE
Release CSS files for instance admins

### ISSUE THREAD

**Issue by ornato-t** [pkrasicki/lemmy-modern-ui-theme-addon#2]
I like the way those themes look and I'd like to add them to my own instance. Could you please save them as .css / .scss files and upload them to the repo?

**Comment by pkrasicki** [comment]
This took some work, but I rewrote some of my JavaScript hacks into CSS hacks. This simplified the JavaScript code and we can now build a stylesheet that can hopefully be used on instances. I'm attaching the CSS files below.

I don't know how themes work in Lemmy, so let me know if any adjustments are needed. If this works, I will add those files to the releases page.

CSS files (designed for Lemmy 0.17 and 0.18):
[lemmy_modern_ui_theme_1.1_css.zip](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/files/11861312/lemmy_modern_ui_theme_1.1_css.zip)

The file `common.css` needs to be used for both themes. Then `light.css` is for light theme and `dark.css` for dark theme. They are meant to be used as an addition to the default themes, not a replacement.

There is one difference between the stylesheet and the addon. It's not possible to remove the colored borders without JavaScript, so comments will look a bit different. I think this should currently be the only difference though.

![lemmy-ui-addon-comments](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/49721209/2e069da4-e15d-4caf-8626-c81567f40019)

![lemmy-ui-addon-stylesheet-comments](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/49721209/cfb47a43-12d7-4dac-aeb2-bd025d9a308a)

**Comment by ornato-t** [comment]
First off, thank you for taking the time to do this. The way custom themes work in Lemmy is rather simple: you put your .css files in a folder (or .scss ones, then build them as .css) and lemmy basically takes care of the rest. This causes the themes to appear in the dropdown in your profile and from there you can select and appply them.

Well I tried doing just that to your themes (a theme can only be one .css file, so I copied the contents of `main.css` into `light` and `dark`) and it didn't work. Here you have a screenshot of how my feed home page looks.

![](https://i.imgur.com/uYTIv4R.png)

Not to worry, though. I think I might now what might be causing this, I had this same error happpen when using themes built for 0.17.4 on 0.18. I don't know what changed in 0.18, but something apparently broke many themes.

I only tested these on my 0.18 dev server. When you say:
> CSS files (designed for Lemmy 0.17 and 0.18)

does that mean your JS hack worked on both versions? To be sure this is the case we'd have to spin up a 0.17 dev server, but I do think your themes might work over there.

**Comment by pkrasicki** [comment]
This addon works with both 0.17 and 0.18. But the way it works is that it applies those styles on top of an existing theme. When I go to a public instance, they usually use a file `styles.css` and then depending on the theme either `litely.css` or `darkly.css`. You can see a list of included styles by typing `document.styleSheets` in browser's console:

![image](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/49721209/a6377139-d812-41a4-8264-5d4ef0943b5d)

I looked at the other alternative themes now and it seems that they are full replacements for the default theme. This is probably what Lemmy is expecting and why my styles didn't work for you. I assumed that maybe there is a way to add extra stylesheets without replacing the default theme entirely. If that's not possible, then you could try copying the code that you have already combined and adding it at the end of the default theme file, but I'm not sure how well that will work.

Could take a screenshot of those theme settings in Lemmy? I'm curious what other options it has.

**Comment by pkrasicki** [comment]
> so I copied the contents of main.css

Is that the default theme file or did you mean the `common.css` file? Because both `light.css` and `dark.css` require the styles from `common.css`. Only then they can be applied on top of the default Lemmy theme.

**Comment by ornato-t** [comment]
> Is that the default theme file or did you mean the `common.css` file? 

My bad, I got confused. Yes I meant your `common.css` file. I copied its contents and added them at the top of both `light.css` and `dark.css`, but that didn't get me very far.

However your explanation gave me an idea. If you are replacing some of the values of litely and darkly with your themes then this leads me to believe that the frontend is likely breaking because some of the classes added by those themes are missing. Tomorrow I will try also adding the contents of litely and darkly to light and dark, along with common.css. Maybe that will work a little better.

> Could take a screenshot of those theme settings in Lemmy? I'm curious what other options it has.

Sure, here you go, but it really isn't as exciting as you might be expecting, the admin panel is overall quite limited. Not that much stuff you can customize (unless you start modding the instance and editing code like I am doing)

![](https://i.imgur.com/wSv23pi.png)

All I can do when it comes to themes is picking a default ones via that selection input. These are the official ones, to add [custom ones](https://join-lemmy.org/docs/administration/theming.html) like I tried to, you simply add the necessary .css files to a certain directory and lemmy automatically pulls them from there.

**Comment by pkrasicki** [comment]
I see, thanks for explaining. I think it should work once you append the contents of `common.css` and `light.css` into litely theme file.

I realised one more thing. By default Lemmy uses both litely and darkly theme and activates only one of them based on user's system theme settings. When you select a custom theme, it will no longer take system settings into account and will always apply only that one theme. This kind of makes sense, since the admin panel lets you choose only one custom theme. So you can have:
- litely + `common.css` + `light.css` - light theme only
- darkly + `common.css` + `dark.css` - dark theme only

Having both of them should also technically be possible. We could combine our modified litely and darkly into one file, but put the contents of litely into `@media (prefers-color-scheme: light) { }` media query and darkly into `@media (prefers-color-scheme: dark) { }`. Such file would be bigger and might make the page load slower, but none of the CSS files (original or mine) are minified. We could reduce their size by removing whitespaces and comments.

**Comment by ornato-t** [comment]
As much as it is a bummer losing browser default theme selection, users can still pick their theme of choice from their user settings, so it's only a problem on their first visit. Wrapping everything in those media query wouldn't really be worth it imo.

Anyway, I have tried merging all those files together and as we both theorized it worked! Here you have a couple screenshots of how it looked, to me everything appears to be working properly:

![immagine](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/53061271/6cf881eb-368f-4bb8-b3ef-f3c2eaa42545)
![immagine](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/53061271/439a3e2f-6a1e-4e77-b1f7-73da7e7ba796)

I think this could be brought a step further by turning these into SASS `.scss` files. That way Lemmy could parse them and possiblly minify them on its own with `yarn themes:build`

**Comment by pkrasicki** [comment]
Awesome! I can see only one small issue. In dark theme the sidebar buttons are supposed to have gray text instead of green:
![lemmy-darkly-gray-buttons](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/49721209/81492bd9-6f3e-446b-98a3-ae41d9b7fcb6)

I don't know what could be causing this though. Maybe merging the files does break some small things. Did you use Lemmy 0.18.0 or master?

>I think this could be brought a step further by turning these into SASS .scss files. That way Lemmy could parse them and possiblly minify them on its own with yarn themes:build

Are you sure Lemmy does that? Because I downloaded CSS files from some instances and they looked normal. Good to know that's an option though.

We need to figure out how to make this as easy to use as possible and at the same time easy to maintain. I think the simplest way would be if I provide one minified CSS file that is a full theme that works out of the box. There would be one based on litely for light theme and one based on darkly for dark theme. The scripts in this repo could be used to build those styles in case someone wants to make modifications. The only problem is reliance on those default themes. I would have to get their CSS code from somewhere (not sure where). And I would have to rebuild the theme each time a new Lemmy version comes out, even if it doesn't break my styles, because the default themes will probably always change a bit and would need to be updated.

So I don't know what the right solution is. It would be best if Lemmy provided a way to attach extra stylesheets in addition to the default theme. Then I wouldn't have to distribute someone else's CSS code and it would still be easy to use.

**Comment by ornato-t** [comment]
> Awesome! I can see only one small issue. In dark theme the sidebar buttons are supposed to have gray text instead of green

Whoops, my bad. Not really sure what I did but I tried this once again and the buttons do indeed appear as grey. Maybe some cache from my previous loadout? We may never know. But it does work and that's all that matters!

> Are you sure Lemmy does that? 

No I am not 😅. I only know that there's a build command, I never bothered checking its outputs. Anyway I don't think minifying is that crucial. I think we should prioritize ease of interaction for admins, rather than performance. 

Something that we could do, would be matching your files with their original counterparts and remove all the duplicate rules from litely and darkly that get overwritten by your files. That should rid us of quite a few lines. Additionally:

> We need to figure out how to make this as easy to use as possible and at the same time easy to maintain

relying on litely and darkly shouldn't be a problem, every instance comes with those enabled and I find it highly unlikely that an admin would manually remove them. Anyway, now that I've bundled litely, light and main together (and same thing for dark on the dark theme side) we saw that it does work. Adding it to lemmy is pretty easy, even for a noob admin. Just copy the file to a certain directory (as instructed by the [docs](https://join-lemmy.org/docs/administration/theming.html)) and that should be it. I'm not even sure if they are required to run the command, in prod lemmy might do this by itself on startup.

**Comment by pkrasicki** [comment]
I'm glad that it works now :).

>Something that we could do, would be matching your files with their original counterparts and remove all the duplicate rules from litely and darkly that get overwritten by your files. That should rid us of quite a few lines.

Is there some easy/automatic way to do that?

So are you saying that admins should merge the files on their own? I guess they would have to repeat that with each Lemmy update? I was hoping to remove that step, but then I would somehow have to build Lemmy's default theme myself to get the CSS file. No idea how I would do that. I would have to do that for each new version of Lemmy.

The theming docs mention Bootstrap 4 by the way and I think they have just migrated to Bootstrap 5 in 0.18 :D.

**Comment by ornato-t** [comment]
I have found a way to merge all files together in a rather clean manner, by using the `@import` directive. This does make the file more readable, but doesn't change anything when it comes to performance, because the browser will still have to download litely and darkly separately. This is how my code looks now. Example from `modern-dark.css`:

```css
/*   IMPORT BASE THEME (darkly.css)   */

@import url("darkly.css");

/*   COMMON CONFIG (common.css)   */

.card, .container-lg .row .col-12.col-lg-6.offset-lg-3.mb-4:first-child, [..]

/*   DARK THEME (dark.css)  */

:root {
    [...]
}
```

Full files: [lemmy-css.zip](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/files/11893124/lemmy-css.zip)

This does solve the issue of updating: as the lemmy devs update `darkly.css`, this will also be updated without needing further changes (of course you might still have to update the stuff from `common.css` and `dark.css`).

And about my previous point of using .scss instead of .css, well I wasn't able to get it to work. But since we have an import direcrive in css too it shouldn't be that big of a deal. 

> Is there some easy/automatic way to do that?

Unfortunately I don't see any easy way of automating the redundancy elimination and minification using strictly CSS. You could however do it in Node, inside your `npm run build-styles` command.
- Download the raw darkly.css file from the latest github version of lemmy. [Link](https://raw.githubusercontent.com/LemmyNet/lemmy-ui/main/src/assets/css/themes/darkly.css)
- Append to it the rules that you would have put inside `main.css` and `dark.css` (with your custom rules going AFTER the original theme, so they'll be higher up in the rule gerarchy)
- Remove the unused CSS with tools such as [PurgeCSS](https://github.com/FullHuman/purgecss)
- Minify the output as needed. I don't know any tools to do that but I'm sure there are plenty
- Release the output as a single .css file for ease of configuration for any admin that would want to include it on their instance

Then the admin only has to grab the latest release of your theme and upload it to their instance.

**Comment by pkrasicki** [comment]
Great ideas! The first approach also makes it easier to implement an automatic theme (I didn't test this yet though):
```
@import url('litely.css') only (prefers-color-scheme: light);
@import url('darkly.css') only (prefers-color-scheme: dark);

/*   COMMON CONFIG (common.css)   */
.card, .container-lg .row .col-12.col-lg-6.offset-lg-3.mb-4:first-child, [..]

@media (prefers-color-scheme: light) {
	/*   LIGHT THEME (light.css)  */
	:root {
    	[...]
	}
}

@media (prefers-color-scheme: dark) {
	/*   DARK THEME (dark.css)  */
	:root {
    	[...]
	}
}
```

The browser will have to make an extra HTTP request to fetch `litely.css` or `darkly.css`. It's not a big issue though and the problem of updates would be completely solved.

Your second solution is also interesting and it would have better performance. It wouldn't be too hard to implement in Node.js. But I think it would require automatic builds. There would have to be a script running on somebody's server that would periodically check for both new Lemmy releases and releases of the addon, fetch the latest theme file and pull from the addon repo, then run a Node.js build script. Then it would push the result to some repo or create a release on GitHub.

The first solution is pretty good already, so we can just do that, unless you want to try to setup those automatic builds somehow :D.

**Comment by pkrasicki** [comment]
I wrote a build script to merge the files and insert the import statement. The theme should work out of the box now. There is even an automatic theme variant :). I created a new release and attached the CSS files there: https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/releases.

Could you test them? It would be great if you could test all 3 variants.

**Comment by ornato-t** [comment]
I've tested all three of your newly released themes and they all work on 0.18!

I'm going to be honest tho, I don't really like your automatic theme selection. The resulting bundle is huge, both litely.css and darkly.css are over 11k lines of CSS and weigh around 260KB each. Including both just to use only one makes the whole thing pretty heavy. 

> It wouldn't be too hard to implement in Node.js. But I think it would require automatic builds. 

I wasn't really thinking of something with automatic builds, more like something that you would run any time you do some edits to the themes, before releasing them on GitHub. Because you might need to touch that code from time to time, if the Lemmy devs edit the way themes work. As I've said already, the switch from 0.17.4 to 0.18 broke a bunch of themes I had downloaded. That might happen again. 

So, my idea was: when you make an edit to the code for whatever reason, you pass your work through that Node script witch outputs a single clean, optimized .css file for one theme, another for the other one (and even an automatic one, if you feel like it), then you upload those to GitHub and create a new release.

Either way, as you said yourself, what we have here works already so if you're not down to do this we could also close the issue and call it a day. I asked for .css files to include in my project and you delivered, can't ask for much more.

**Comment by pkrasicki** [comment]
I'm glad to hear they work :).

>I'm going to be honest tho, I don't really like your automatic theme selection. The resulting bundle is huge, both litely.css and darkly.css are over 11k lines of CSS and weigh around 260KB each. Including both just to use only one makes the whole thing pretty heavy.

Are you sure that's the case? Maybe it doesn't work the way I thought it does or I made some mistake, but only one of them should be included.
```
@import url("litely.css") (prefers-color-scheme: light);
@import url("darkly.css") (prefers-color-scheme: dark);
```

CSS allows to have conditional imports with media queries. It should import only one theme depending on the settings. At least that's the theory. It's possible I did it wrong (I couldn't find a good example), but if both of the themes were really included, I don't think the light theme would work.

The other themes are way bigger, so I'm hoping mine will break less (0.18 didn't break it much). If I include all the styles just like they do, then it will probably break as much as the other themes. So it would have to be updated more often. Lemmy 0.18 is easier to style (it uses CSS variables), so I'm hoping to simplify this theme even more in the future.

**Comment by pkrasicki** [comment]
I was wrong. It works exactly like you said, my mistake.

I have a new idea for the auto theme. Maybe you could try it when you have the time:
[modern-theme-1.2-auto.zip](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/files/11926199/modern-theme-1.2-auto.zip)

1. Download the new files. All that I've changed is the import.
2. Rename your `litely.css` to `litely-original.css` and `darkly.css` to `darkly-original.css`.
3. Rename `modern-light-auto.css` to `litely.css` and `modern-dark-auto.css` to `darkly.css`.
4. Change your instance theme to "Browser Default".

This should then use Lemmy's default mechanism for switching themes, which only downloads one stylesheet at a time, so it's more efficient.

**Comment by subashz** [comment]
Hey, thanks for the theme. I have used the theme in my instance: https://hamro.world/ : Just one small problem while selecting the local tab post(black selected text color) -> white . https://imgur.com/a/nDYjFmO

**Comment by pkrasicki** [comment]
@subashz hi, that was an issue caused by changes in Lemmy 0.18.2. I have created a new release with a fix. The buttons will now have correct colors.
