### ISSUE TITLE
How can we add more instance support?

### ISSUE THREAD

**Issue by linux-cultist** [pkrasicki/lemmy-modern-ui-theme-addon#4]
There is 1370 instances now in the lemmy network, and adding support for all of them would be nice somehow.

Probably easiest if you could distribute this theme as something instance owners can install.

**Comment by pkrasicki** [comment]
The list of supported instances is [hardcoded in file manifest.json](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/blob/master/manifest.json#L14). I add new ones when requested by users. Supporting all of them would be nice, but I'm not sure if it's a good idea to have such a long list.

The theme can already be used on instances. You can download the CSS files from the [Releases page](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/releases).

**Comment by linux-cultist** [comment]
Thanks a lot. Closing this. :)

**Comment by pkrasicki** [comment]
All Lemmy instances are now supported in the latest 1.3.2 release. There is no hardcoded list anymore.

**Comment by linux-cultist** [comment]
That's really great, will try it right away :)
