### ISSUE TITLE
Add a setting to allow users to add instances

### ISSUE THREAD

**Issue by wason-sonico** [pkrasicki/lemmy-modern-ui-theme-addon#5]
Hi. Can you add a setting where users can add instances? Thanks!

**Comment by pkrasicki** [comment]
Hi, currently I add new instances on user request. Letting users configure their own list would be a solution to this problem, but it would make the addon more complicated.

Another way could be for the addon to automatically detect if the visited website is a Lemmy instance. This could be easier to implement and users wouldn't have to configure anything. Maybe this is the best solution? The only issue is that if Lemmy developers remove whatever information we use for this detection, we would have a problem with future Lemmy versions.

It would be best if instance owners used this theme on their instances (the files can be downloaded from the Releases page). Then the addon wouldn't even be necessary - we would only maintain a simple theme. But this probably won't happen.

**Comment by wason-sonico** [comment]
Well besides the issue you mentioned if you add the detection it also means the add-on will require access to all websites right?

**Comment by pkrasicki** [comment]
Yes and it would be the same if we made the list configurable. In both cases it would need permission to access all websites.

**Comment by wason-sonico** [comment]
Ah. I didn't know that. Well then feel free to implement what you consider best. Thanks!

**Comment by pkrasicki** [comment]
Automatic detection is now implemented in the latest release. Feel free to create an issue if you find any problems.
