### ISSUE TITLE
lemmy.dbzer0.com not detected

### ISSUE THREAD

**Issue by KairuByte** [pkrasicki/lemmy-modern-ui-theme-addon#7]
As the title says, navigating to lemmy.dbzer0.com does not seem to kick the extension into working. It remains "disabled"/"uninitiated".

**Comment by pkrasicki** [comment]
The addon does work for me, but it was designed to work with the default theme. So it doesn't remove all of the custom changes on that instance.

With addon **disabled**:
![dbzer0-before1](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/49721209/899e9101-76d7-4fbb-a298-392afbe7bfe6)

![dbzer0-before2](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/49721209/99fbf7b1-429b-4af8-9ccf-b9cf88b21c9f)


With addon **enabled**:
![dbzer0-after1](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/49721209/c8632207-fb4f-4715-ad5d-9e1508fd3340)

![dbzer0-after2](https://github.com/pkrasicki/lemmy-modern-ui-theme-addon/assets/49721209/1f751c10-2b3d-4f4f-b359-02462c81e2d1)

It doesn't fully work, but it removes some of the distractions. Adding a workaround for every custom theme probably wouldn't be a good idea. But if you have an account on that instance, you could try changing the theme in settings and see if that helps.
